"""Budgets and settings of the agent loop."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

MBPP_MAX_ITERATIONS = 10
MBPP_MAX_INPUT_TOKENS = 6_000
MBPP_MAX_OUTPUT_TOKENS = 1_500
MBPP_MAX_WALL_TIME_SECONDS = 120
MBPP_MCP_SERVER = PROJECT_ROOT / "mcp_tools_mbpp.py"
SW_BENCH_TOOLS = PROJECT_ROOT / "mcp_tools_swebench.py"

SWEBENCH_MAX_ITERATIONS = 30
SWEBENCH_MAX_INPUT_TOKENS = 300_000
SWEBENCH_MAX_OUTPUT_TOKENS = 10_000
SWEBENCH_MAX_WALL_TIME_SECONDS = 900
SWEBENCH_SANDBOX_TIMEOUT_SECONDS = 90
SWEBENCH_DEFAULT_TESTBED = "/testbed"

MBPP_LIMITS = {
    "iterations": MBPP_MAX_ITERATIONS,
    "input": MBPP_MAX_INPUT_TOKENS,
    "output": MBPP_MAX_OUTPUT_TOKENS,
    "wall_time": MBPP_MAX_WALL_TIME_SECONDS,
}
SWEBENCH_LIMITS = {
    "iterations": SWEBENCH_MAX_ITERATIONS,
    "input": SWEBENCH_MAX_INPUT_TOKENS,
    "output": SWEBENCH_MAX_OUTPUT_TOKENS,
    "wall_time": SWEBENCH_MAX_WALL_TIME_SECONDS,
}

MAX_TOKENS_PER_REQUEST = 2048
DEFAULT_TEMPERATURE = 0.0

MAX_CONSECUTIVE_ERRORS = 3
EXIT_MARGIN_SECONDS = 10
REQUEST_TIMEOUT_SECONDS = 60.0
MAX_EMPTY_RESPONSES = 2
MAX_WAITS = 3
WAIT_SECONDS = 20.0
PAUSE_BEFORE_ABORT_SECONDS = 60.0
FALLBACK_STATUSES = {404, 408, 413, 429, 500, 502, 503, 504}
MAX_LIMITS_CHARS = 250
LAST_CALL_STEPS = 2
LAST_CALL_TOKEN_RATIO = 0.8

INTACT_TURNS = 10
MAX_OBS_CHARS = 100
CHARS_PER_TOKEN = 4
BUDGET_MARGIN = 0.9

BACKUP_DIR = PROJECT_ROOT / "backup_memory"
BACKUP_FILE = BACKUP_DIR / "backup.json"
