from typing import List
from pydantic import BaseModel, Field


class SandboxConfig(BaseModel):
    """Sandbox configuration for student solutions.
    Uses allowlist approach: only imports in authorized_imports are allowed.
    Everything else is blocked by default.
    """

    max_execution_time_seconds: int = 30
    max_memory_mb: int = 512
    max_output_length: int = 10000
    # TODO add a way to configure allowed directories for file access and add
    # security checks in the sandbox to prevent access to other directories
    allowed_directories: List[str] = Field(
        default_factory=lambda: ["/testbed", "/tmp/agent"]
    )
    authorized_imports: List[str] = Field(
        default_factory=lambda: [
            "math",
            "math.*",
            "random",
            "datetime",
            "datetime.*",
            "time",
            "itertools",
            "functools",
            "collections",
            "collections.*",
            "operator",
            "string",
            "re",
            "json",
            "decimal",
            "fractions",
            "statistics",
            "heapq",
            "bisect",
            "array",
            "copy",
            "types",
            "weakref",
            "enum",
            "contextlib",
            "abc",
            "typing",
            "typing.*",
            "cmath",
        ]
    )
    authorized_builtins: List[str] = Field(
        default_factory=lambda: [
            "bool",
            "int",
            "float",
            "complex",
            "str",
            "bytes",
            "bytearray",
            "list",
            "tuple",
            "dict",
            "set",
            "frozenset",
            "slice",
            "range",
            "object",
            "type",
            "isinstance",
            "issubclass",
            "callable",
            "iter",
            "next",
            "enumerate",
            "zip",
            "map",
            "filter",
            "reversed",
            "sorted",
            "sum",
            "min",
            "max",
            "all",
            "any",
            "len",
            "abs",
            "round",
            "divmod",
            "pow",
            "repr",
            "format",
            "ascii",
            "chr",
            "ord",
            "bin",
            "oct",
            "hex",
            "hash",
            "super",
            "property",
            "staticmethod",
            "classmethod",
            "print",
            "Exception",
            "BaseException",
            "ValueError",
            "TypeError",
            "KeyError",
            "IndexError",
            "StopIteration",
            "StopAsyncIteration",
            "RuntimeError",
            "AttributeError",
            "NotImplementedError",
            "ImportError",
            "ModuleNotFoundError",
            "NameError",
            "ZeroDivisionError",
            "ArithmeticError",
            "OverflowError",
            "OSError",
            "FileNotFoundError",
            "PermissionError",
            "TimeoutError",
            "MemoryError",
            "RecursionError",
            "AssertionError",
            "LookupError",
            "UnicodeError",
            "GeneratorExit",
            "KeyboardInterrupt",
            "SystemExit",
        ]
    )
    authorized_attributes: List[str] = Field(
        default_factory=lambda: [
            "__class__",
            "__bases__",
            "__base__",
            "__mro__",
            "__subclasses__",
            "__globals__",
            "__reduce__",
            "__reduce_ex__",
            "__init_subclass__",
            "__init__",
            "__new__",
            "__call__",
            "__str__",
            "__repr__",
            "__format__",
            "__sizeof__",
            "__dir__",
            "__doc__",
            "__module__",
            "__annotations__",
            "__kwdefaults__",
            "__defaults__",
            "__code__",
            "__closure__",
            "__func__",
            "__self__",
            "__dict__",
            "__weakref__",
            "__slots__",
            "__getattribute__",
        ]
    )
